### ISSUE TITLE
humans compagnons fait crash mon serveur depusi peu 

### ISSUE THREAD

**Issue by ptilourg** [justinwon777/HumanCompanions#42]
bonjour humans compagnons fait crash mon serveur depuis peu , jusqu'a aujourd'hui tout fonctionné bien , maintenant mon serveur sur gportal crash avec comme code erreur : 

"net.minecraft.world.entity.TamableAnimal.m_21826_()" is null
at com.github.justinwon777.humancompanions.entity.ai.AvoidCreeperGoal.m_8056_(AvoidCreeperGoal.java:71) ~[humancompanions-1.19.2-1.4.7.jar%23116!/:1.19.2-1.4.7] {re:classloading}
at net.minecraft.world.entity.ai.goal.WrappedGoal.m_8056_(WrappedGoal.java:41) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:classloading}
at net.minecraft.world.entity.ai.goal.GoalSelector.m_25373_(GoalSelector.java:106) ~[server-1.19.2-20220805.130853-srg.jar%23138!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}

Pouvez vous régler le problème s'il vous plait

**Comment by norfaremc** [comment]
My server keeps crashing due to this issue. At this point the server is unplayable. Please fix this issue.
